### ISSUE TITLE
Could not resolve com.razorpay:customui:3.9.+.

### ISSUE THREAD

**Issue by skalex4** [razorpay/razorpay-flutter-customui#53] opened 2022-10-31 05:35 UTC
Razorpay maven server XML urls are throwing 403. 

Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:customui:3.9.+.
     Required by:
         project :app > project :razorpay_flutter_customui
      > Failed to list versions for com.razorpay:customui.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/customui/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/customui/maven-metadata.xml'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
Exception: Gradle task assembleDebug failed with exit code 1

-- @vivekshindhe @ramprasadAnand @razorraghib  Please provide a fix for this asap.

**Comment by AamilLiveKeeping** [comment] 2022-10-31 08:04
@skalex4 Facing the same issue please give update ASAP I am trying to solve since last 4 hrs
-- @vivekshindhe @ramprasadAnand @razorraghib

**Comment by skalex4** [comment] 2022-11-01 04:08
@AamilLiveKeeping Seriously. I tried to contact support yesterday afternoon. 
they told us that they'll provide the fix at the earliest. 
But still no fix.

-- @vivekshindhe @ramprasadAnand @razorraghib Requestiing you to please provide the fix as soon as possible.. 
our releases have stalled because we are unable to generate the builds.

**Comment by AamilLiveKeeping** [comment] 2022-11-01 08:27
@skalex4 I think issue is resolved now i am able run app

**Comment by niteshdkart** [comment] 2022-11-01 13:16
@skalex4 I also face same issue yesterday and today it solved automatically , now I can able to build app. For me also it looks that the issue is from Jcenter() as their website also contains about this issue. As they said yesterday they are working on resolving it , today it resolves.

**Comment by skalex4** [comment] 2022-11-01 16:03
yes, @niteshdkart  

They deployed the fix by 1 o'clock today, and it's working after that. 

I think they change to maven from Jcenter.

**Comment by vivekshindhe** [comment] 2022-11-03 10:18
Issue fixed on v1.3.3. Basically removed jcenter from the build.gradle file. Thank you for you patience.

**Closed by vivekshindhe** 2022-11-03 10:18 UTC
